name: First Workflow
# on definiert das Event welches den Workflow triggert
# workflow_dispatch ist ein spezielle Event das auf eine Benutzer-Eingabe wartet
on: workflow_dispatch
# jobs sagt was zu tun ist
jobs:
  # kannst du nenen wie du willst
  first-job:
    # runs-on definert den runner, also die notwendige Umgebung
    # siehe https://docs.github.com/de/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    # stepa 1 von n eines job. Jeder - entspricht eine step. - name ist z.B. ein step
    steps:
      - name: Print greeding
      run: echo "Hello World"
      - name: Print godbye
      run: echo "Done - bye!"
