name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeding
      - run: echo "Hello World"
      - name: Print godbye
      - run: echo "Done - bye!"
